### ISSUE TITLE
Problème d'encoding non-UTF-8

### ISSUE THREAD

**Issue by PowerKiKi** [AlainSchoebi/ichtus-reservations#2]
Je constate qu'il y a encore des problèmes d'encoding des fichiers sources en non-UTF-8. Cela a pour effet que tous les accents apparaissent comme des "?", comme dans l'image ci-dessous.

La façon la plus simple de corriger cela est de s'assurer que tous tes fichiers soit toujours en UTF-8 et que ton éditeur de code soit configurer pour écrire que du UTF-8 pour les fichiers future (si ce genre de paramètre existe pour ton éditeur).

![image](https://user-images.githubusercontent.com/72603/51110225-04e1d180-184c-11e9-955e-da88bc718bfc.png)

**Comment by PowerKiKi** [comment]
Je crois que tu utilises Visual Studio Code. Dans ce cas cette question sur SO devrait t'aider à résoudre le souci: https://stackoverflow.com/a/40365121/37706

**Comment by AlainSchoebi** [comment]
Oui ça a fonctionné merci beaucoup !
