### ISSUE TITLE
Image manquantes

### ISSUE THREAD

**Issue by PowerKiKi** [AlainSchoebi/ichtus-reservations#4]
Plusieurs images ne peuvent pas être chargées correctement. Ceci est dû à la casse des noms de fichiers sur disque et dans les sources qui est différente.

La majorité des système de fichiers sont sensible à la casse. macOS est le seul système grand public qui est insensible. Si tu travaille sur macOS il faut donc faire particulièrement attention à ce problème, car cela peut fonctionner chez toi, mais ne fonctionnera pas quasiment partout ailleurs.

![image](https://user-images.githubusercontent.com/72603/54736750-e1575080-4c19-11e9-900b-09ff66a6daac.png)

**Comment by AlainSchoebi** [comment]
Ces images n'existent pas encore, c'est pour cela qu'il ne les trouvait pas... J'étais pas encore sûr si les catégories (des embarcations) que j'avais mises en place étaient définitives ou pas.
Je travaille pas sur mac, mais faudrait-il que je renomme mes fichiers avec seulement des minuscules ou cela n'est pas forcémment nécessaire ?

**Comment by PowerKiKi** [comment]
Effectivement `Aviron.png` et `Voile.png` existe pas du tout. En revanche `Sup.png`, le seul que j'avais vérifié, existe bel et bien. Et au moins celui-là devrait être corrigé.

> faudrait-il que je renomme mes fichiers avec seulement des minuscules

Ce n'est pas absolument obligatoire, mais c'est une pratique courante, et moi-même je le fais toujours. Garder que des noms en minuscule, sans espace, et sans caractères "exotiques" (pas d'accents), est un moyen facile de ne jamais avoir de problème. Et donc de s'économiser des ennuis plus tard. Si c'était mon projet, je changerais partout.

**Comment by PowerKiKi** [comment]
Tu as fermer ce ticket, mais je continue de voir une erreur pour SUP.png avec la dernière version du code:

![image](https://user-images.githubusercontent.com/72603/55375796-5d368e80-5572-11e9-90ad-32592573bdd6.png)

Est-ce que tu as corrigé chez toi, mais pas encore publier ton code ? ou est-ce que cette image est passée entre les gouttes et devrait encore être corrigée ?

**Comment by AlainSchoebi** [comment]
Hello, oui merci le fichier n'était pas encore corrigé ! Mais cela devrait être bon maintenant.
Visual studio ne remarquait pas que le nom du fichier avait changé, car seulement les majuscules/minsucules changeaient :)
